services:
  # --- INFRASTRUCTURE ---
  vault:
    image: hashicorp/vault:1.21
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - vault_data:/vault/file
      - ./vault/scripts:/scripts
    cap_add:
      - IPC_LOCK
    command: server
    networks:
      - transcendence_net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379"
    networks:
      - transcendence_net

  postgres:
    image: postgres:16
    container_name: transcendence
    restart: always
    env_file:
      - ./micro/db/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_micro_data:/var/lib/postgresql/data
    networks:
      - transcendence_net

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - transcendence_net

  # --- MICROSERVICES ---
  gateway:
    build:
      context: ./micro
      dockerfile: ./apps/gateway/Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./micro/apps/gateway/.env
    networks:
      - transcendence_net
    depends_on:
      - vault

  auth:
    build:
      context: ./micro
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth
    restart: always
    env_file:
     - ./micro/apps/auth/.env
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_started
      vault:
        condition: service_started
    networks:
      - transcendence_net

  game:
    build:
      context: ./micro
      dockerfile: ./apps/game/Dockerfile
    container_name: game
    restart: on-failure
    stop_grace_period: 10s
    env_file:
      - ./micro/apps/game/.env
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    networks:
      - transcendence_net

  friends:
    build:
      context: ./micro
      dockerfile: ./apps/friends/Dockerfile
    container_name: friends
    restart: always
    env_file:
      - ./micro/apps/friends/.env
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    networks:
      - transcendence_net

  # --- FRONTENDS ---
  frontend:
    build:
      context: ./my-game
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5173:5173"
    restart: always
    networks:
      - transcendence_net

  ping_game:
    build:
      context: ./ping_game
      dockerfile: Dockerfile
    container_name: game_server
    ports:
      - "8082:8082"
      - "5001:5001"
    env_file:
      - ./ping_game/.env
    networks:
      - transcendence_net

  ping_game_solo:
    build:
      context: ./ping_game_solo
      dockerfile: Dockerfile
    container_name: game_server_solo
    ports:
      - "8083:8083"
      - "5002:5002"
    env_file:
      - ./ping_game_solo/.env
    networks:
      - transcendence_net

##################################
  nginx:
    build: ./nginx
    container_name: pingpong-nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - gateway
      - frontend
    networks:
      - transcendence_net

#####################################
volumes:
  postgres_micro_data:
  vault_data:

networks:
  transcendence_net:
    driver: bridge


